name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation (Light)
        uses: Platane/snk@v3
        with:
          github_user_name: Laluprasad1
          outputs: |
            dist/snake.svg

      - name: Generate Snake Animation (Dark)
        uses: Platane/snk@v3
        with:
          github_user_name: Laluprasad1
          outputs: |
            dist/snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAKE_COLOR: "#00ff9c"
          BACKGROUND_COLOR: "#0d1117"

      - name: Push Snake Animations
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
